### ISSUE TITLE
Support loading/writing and customizing OCI runtime spec

### ISSUE THREAD

**Issue by mrunalp** [cri-o/cri#22]
We need to write the code that supports:
* Reading OCI runtime config.json
* Writing OCI runtime config.json
* Converting k8s CRI types to config.json

**Comment by harche** [comment]
https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/agent/oci/src/lib.rs#L31

**Comment by harche** [comment]
I think kata agent 2.0 code already has code to read config.json, but not sure why they haven't spun it out in a separate crate so that others can use it too. https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/agent/oci/src/lib.rs#L61

**Comment by saschagrunert** [comment]
There are multiple crates already supporting the runtime spec. It's a tricky question if we want to copy the code to allow easier modifications or rely on a probably unmaintained crate. :thinking:

**Comment by harche** [comment]
Kata is just about to release their agent based on rust, so I am hopeful it would be maintained. So maybe we can convince them to take the runtime spec out in a separate crate (and repo).

**Comment by saschagrunert** [comment]
It's done! :grin: (#49)
