### ISSUE TITLE
Decide on a name

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri#27]
cri was just a place holder, because naming things is hard. `cri` doesn't really uniquely identify this project (cri implementation in rust).

A couple of ideas floated around so far:
- Crustacean puns:
  - https://en.wikipedia.org/wiki/Krill 
    - crill
  - https://en.wikipedia.org/wiki/Amphipoda
    - This is the phyllum of crustaceans (and has pods in the name)
- Rust pun
  - Crrust (container runtime-rust)?

- Container pun
    - Casket

- Oxidation pun
  - Ctrized (like container-dized)
  - Containerized

- Runc pun
  - rustc

bringing this up in an issue for discussion. I personally am leaning towards crrust (easy to say, clear about what it is)

**Comment by saschagrunert** [comment]
I'm also in favor of `crust`, even if the crate name is already taken. We could still use `crust-rs`.

New proposal:
- `cri-rs`

**Comment by saschagrunert** [comment]
Any objections? :D

**Comment by harche** [comment]
`crust` +1

**Comment by haircommander** [comment]
I vote `crrust`, as it could be `container runtime rust` which I find clear enough. it would also give slightly better google-ability as we won't drown in results for pizza :smile:

**Comment by saschagrunert** [comment]
I’m fine with crrust, too. WDYT @harche ?

**Comment by harche** [comment]
@saschagrunert that sounds good too. So the pronunciation would be c-r-rust or like the word crust (as in pizza)? @haircommander

**Comment by saschagrunert** [comment]
@harche I think so. I can imagine many delicious logos around that name, too. 🤤

**Comment by haircommander** [comment]
agreed, still pronounced as crust :pizza:

**Comment by saschagrunert** [comment]
So, do we wanna rename this repo? 😬

**Comment by rhatdan** [comment]
Why not krust?

**Comment by saschagrunert** [comment]
> Why not krust?

Oh, that sounds good to me, too. The crate name is also free. 😱

**Comment by rhatdan** [comment]
How about 
krustd - (Prounounced like CRUSTY)
Kubenernets Rust Daemon

**Comment by haircommander** [comment]
+1 for krustd

**Comment by rhatdan** [comment]
Logo https://i.pinimg.com/originals/b1/9b/c2/b19bc29fb72e2f4b9f11d8daa5290a86.jpg

**Comment by saschagrunert** [comment]
> Logo https://i.pinimg.com/originals/b1/9b/c2/b19bc29fb72e2f4b9f11d8daa5290a86.jpg

Definitely +1 for krustd, this made my day!

Can we discuss the logo? 😅

**Comment by saschagrunert** [comment]
The scope of the project seems to shift to a container library which supports some default implementations like the Kubernetes CRI or CNI. I think the name should reflect that. My latest proposal is: `containrs`
